# Google App Engine Configuration
runtime: nodejs18

env_variables:
  NODE_ENV: "production"
  JWT_SECRET: "moroccan_heritage_jwt_secret_2024"
  SESSION_SECRET: "moroccan_session_secret_2024"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "Patrimoine2024!"
  ADMIN_EMAIL: "admin@patrimoine.gov.ma"

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
